trigger:
  - main

variables:
  - group: TravelMemory-Vars

jobs:
  - deployment: DeployToVM
    environment: 
      name: 'TravelMemory-VM'
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self  
            
            # This explicitly injects Node.js & NPM into the pipeline agent's PATH
            - task: NodeTool@0
              inputs:
                versionSpec: '18.x'
              displayName: 'Install Node.js'
            
            # Clean up: Kill ONLY our app servers, not the pipeline agent!
            - script: |
                sudo pkill -f "node index.js" || true
                sudo pkill -f "react-scripts" || true
              displayName: 'Stop previous servers'

            # ---------------------------------------------
            # BACKEND DEPLOYMENT
            # ---------------------------------------------
            - script: |
                cd $(System.DefaultWorkingDirectory)/backend
                
                echo "MONGO_URI=$(MONGO_URI)" > .env
                echo "PORT=$(BACKEND_PORT)" >> .env
                
                npm install
                
                # Because we used NodeTool@0, 'node' will now be found
                # Added sudo env PATH=$PATH $(which node) so Azure DevOps can't kill it!
                sudo env PATH=$PATH nohup $(which node) index.js </dev/null > backend.log 2>&1 &

              displayName: 'Deploy Backend'


            # ---------------------------------------------
            # FRONTEND DEPLOYMENT
            # ---------------------------------------------
            - script: |
                cd $(System.DefaultWorkingDirectory)/frontend
      
                echo "REACT_APP_BACKEND_URL=$(REACT_APP_BACKEND_URL)" > .env
                
                npm install
                
                # We use env PATH=$PATH and $(which npm) so sudo doesn't lose track of NPM
                sudo BROWSER=none PORT=80 env PATH=$PATH nohup $(which npm) start </dev/null > frontend.log 2>&1 &
              displayName: 'Deploy Frontend'

            # ---------------------------------------------
            # FIX PERMISSIONS FOR THE NEXT RUN
            # ---------------------------------------------
            - script: |
                sudo chown -R $USER:$USER $(System.DefaultWorkingDirectory)
              displayName: 'Fix Folder Permissions for Next Run'
              condition: always()
